import { AbstractControl, ValidationErrors } from "@angular/forms";

export class CityValidator{
   
    static City(control: AbstractControl): ValidationErrors | null {
        
        const enteredCity = control.value;
        const isSerbianCity = serbianCities.includes(enteredCity);
    
        return isSerbianCity ? null : { notSerbianCity: true };
      }
    }
      const serbianCities: string[] = [
        "Ada",
        "Aleksandrovac",
        "Aleksinac",
        "Alibunar",
        "Apatin",
        "Aranđelovac",
        "Arilje",
        "Babušnica",
        "Bajina Bašta",
        "Batocina",
        "Bač",
        "Bačka Palanka",
        "Bačka Topola",
        "Bački Petrovac",
        "Bela Palanka",
        "Bela Crkva",
        "Beočin",
        "Bečej",
        "Blace",
        "Bogatić",
        "Bojnik",
        "Boljevac",
        "Bosilegrad",
        "Brus",
        "Bujanovac",
        "Varvarin",
        "Velika Plana",
        "Veliko Gradište",
        "Vitina",
        "Vladimirci",
        "Vladimirci",
        "Vlasotince",
        "Vrbas",
        "Vrnjačka Banja",
        "Vučitrn",
        "Gadžin Han",
        "Glogovac",
        "Gnjilane",
        "Žabalj",
        "Žabari",
        "Žagubica",
        "Žitište",
        "Žitorađa",
        "Zvečan",
        "Zubin Potok",
        "Ivanjica",
        "Inđija",
        "Irig",
        "Istok",
        "Kanjiža",
        "Kačanik",
        "Kladovo",
        "Klina",
        "Knić",
        "Knjaževac",
        "Kosovska Kamenica",
        "Kosovska Mitrovica",
        "Kočeljeva",
        "Kruševac",
        "Kula",
        "Kuršumlija",
        "Kučevo",
        "Lajkovac",
        "Lapovo",
        "Leban",
        "Leposavić",
        "Lipjan",
        "Ljubovija",
        "Ljig",
        "Majdanpek",
        "Mali Zvornik",
        "Mali Iđoš",
        "Malo Crniće",
        "Medveđa",
        "Merošina",
        "Mionica",
        "Negotin",
        "Nova Varoš",
        "Nova Crnja",
        "Novi Bečej",
        "Novi Kneževac",
        "Novo Brdo",
        "Obilić",
        "Opovo",
        "Orahovac",
        "Osojane",
        "Pantelej",
        "Paraćin",
        "Petrovac na Mlavi",
        "Peć",
        "Pećinci",
        "Plandište",
        "Podujevo",
        "Požega",
        "Preševo",
        "Priboj",
        "Priština",
        "Prijepolje",
        "Ražanj",
        "Rača",
        "Raška",
        "Rekovac",
        "Ruma",
        "Svilajnac",
        "Svrljig",
        "Senta",
        "Sečanj",
        "Sjenica",
        "Smederevska Palanka",
        "Sokobanja",
        "Srbica",
        "Srbobran",
        "Sremski Karlovci",
        "Stara Pazova",
        "Suva Reka",
        "Surdulica",
        "Srbica",
        "Temerin",
        "Titel",
        "Topola",
        "Trgovište",
        "Trstenik",
        "Tutin",
        "Ćićevac",
        "Ćuprija",
        "Ub",
        "Uroševac",
        "Crna Trava",
        "Čajetina",
        "Čoka",
        "Šid",
        "Štimlje",
        "Štrpce",
        'Belgrade',
        'Novi Sad',
        'Niš',
        'Kragujevac',
        'Subotica',
        'Zrenjanin',
        'Pančevo',
        'Čačak',
        'Kraljevo',
        'Smederevo',
        'Leskovac',
        'Valjevo',
        'Novi Pazar',
        'Kruševac',
        'Vranje',
        'Šabac',
        'Užice',
        'Požarevac',
        'Pirot',
        'Bor'
      ];
   